import { Question } from "./types";

export const questions: Question[] = [
  {
    id: "1",
    text: "Какая нота является основной в до мажоре?",
    options: ["До", "Ре", "Ми", "Фа"],
    correctAnswer: 0,
    difficulty: ["beginner"],
    requiresMicrophone: false,
    quizType: ["serious"],
    category: "theory",
  },
  {
    id: "2",
    text: "Спойте ноту Ля (440 Гц) и запишите её",
    options: ["Выполнено", "Не получилось"],
    correctAnswer: 0,
    difficulty: ["advanced", "professional"],
    requiresMicrophone: true,
    quizType: ["serious"],
    category: "technique",
  },
  {
    id: "3",
    text: "Что делает певец, когда забывает слова?",
    options: ["Мямлит", "Танцует", "Издает странные звуки", "Все варианты"],
    correctAnswer: 3,
    difficulty: ["beginner", "amateur", "advanced", "professional"],
    requiresMicrophone: false,
    quizType: ["fun"],
    category: "theory",
  },
  {
    id: "4",
    text: "Что такое диафрагмальное дыхание?",
    options: [
      "Дыхание грудью",
      "Дыхание животом",
      "Поверхностное дыхание",
      "Задержка дыхания",
    ],
    correctAnswer: 1,
    difficulty: ["beginner", "amateur"],
    requiresMicrophone: false,
    quizType: ["serious"],
    category: "technique",
  },
  {
    id: "5",
    text: "Спойте гамму до мажор вверх и вниз",
    options: ["Выполнено", "Нужна помощь"],
    correctAnswer: 0,
    difficulty: ["amateur", "advanced"],
    requiresMicrophone: true,
    quizType: ["serious"],
    category: "technique",
  },
  {
    id: "6",
    text: "Какой напиток лучше НЕ пить перед пением?",
    options: ["Теплая вода", "Молоко", "Травяной чай", "Медовая вода"],
    correctAnswer: 1,
    difficulty: ["beginner", "amateur", "advanced"],
    requiresMicrophone: false,
    quizType: ["serious", "fun"],
    category: "theory",
  },
  {
    id: "7",
    text: "Определите на слух: это мажор или минор? (аудио)",
    options: ["Мажор", "Минор", "Не могу определить", "Это хроматизм"],
    correctAnswer: 0,
    difficulty: ["advanced", "professional"],
    requiresMicrophone: false,
    quizType: ["serious"],
    category: "ear-training",
  },
  {
    id: "8",
    text: "Что означает 'попасть в ноты'?",
    options: [
      "Уронить ноты на пол",
      "Петь точно по высоте",
      "Быстро читать ноты",
      "Импровизировать",
    ],
    correctAnswer: 1,
    difficulty: ["beginner"],
    requiresMicrophone: false,
    quizType: ["serious", "fun"],
    category: "theory",
  },
  {
    id: "9",
    text: "Спойте с вибрато на любой ноте",
    options: ["Получилось", "Нужна практика", "Что такое вибрато?"],
    correctAnswer: 0,
    difficulty: ["advanced", "professional"],
    requiresMicrophone: true,
    quizType: ["serious"],
    category: "technique",
  },
  {
    id: "10",
    text: "Как называется самый высокий женский голос?",
    options: ["Сопрано", "Меццо-сопрано", "Контральто", "Тенор"],
    correctAnswer: 0,
    difficulty: ["beginner", "amateur"],
    requiresMicrophone: false,
    quizType: ["serious"],
    category: "theory",
  },
  {
    id: "11",
    text: "Что делать, если на репетиции началась икота?",
    options: [
      "Продолжать петь",
      "Сделать 3 глотка воды",
      "Спеть громче",
      "Изобразить это как вокальный прием",
    ],
    correctAnswer: 3,
    difficulty: ["beginner", "amateur", "advanced", "professional"],
    requiresMicrophone: false,
    quizType: ["fun"],
    category: "theory",
  },
  {
    id: "12",
    text: "Повторите мелодическую фразу (аудио)",
    options: ["Выполнено", "Сложно", "Нужно повторить"],
    correctAnswer: 0,
    difficulty: ["amateur", "advanced", "professional"],
    requiresMicrophone: true,
    quizType: ["serious"],
    category: "ear-training",
  },
  {
    id: "13",
    text: "Что такое 'а капелла'?",
    options: [
      "Пение с микрофоном",
      "Пение без accompaniment",
      "Итальянская песня",
      "Быстрое пение",
    ],
    correctAnswer: 1,
    difficulty: ["beginner", "amateur"],
    requiresMicrophone: false,
    quizType: ["serious"],
    category: "theory",
  },
  {
    id: "14",
    text: "Спойте стаккато на примере 'ла-ла-ла'",
    options: ["Выполнено", "Не понимаю задание", "Получилось нечетко"],
    correctAnswer: 0,
    difficulty: ["advanced", "professional"],
    requiresMicrophone: true,
    quizType: ["serious"],
    category: "technique",
  },
  {
    id: "15",
    text: "Какой вокальный прием используют в рок-музыке?",
    options: ["Белый звук", "Гроулинг", "Фальцет", "Все варианты"],
    correctAnswer: 3,
    difficulty: ["amateur", "advanced"],
    requiresMicrophone: false,
    quizType: ["serious"],
    category: "theory",
  },
  {
    id: "16",
    text: "Что означает 'петь в унисон'?",
    options: [
      "Петь одну и ту же ноту",
      "Петь разные ноты",
      "Петь без аккомпанемента",
      "Петь очень громко",
    ],
    correctAnswer: 0,
    difficulty: ["beginner"],
    requiresMicrophone: false,
    quizType: ["serious"],
    category: "theory",
  },
  {
    id: "17",
    text: "Исполните любой вокальный riff (импровизация)",
    options: ["Выполнено", "Сложно импровизировать", "Что такое riff?"],
    correctAnswer: 0,
    difficulty: ["professional"],
    requiresMicrophone: true,
    quizType: ["serious", "fun"],
    category: "technique",
  },
  {
    id: "18",
    text: "Как называется быстрая смена нот в джазе?",
    options: ["Скат", "Глиссандо", "Вибрато", "Мелизм"],
    correctAnswer: 0,
    difficulty: ["advanced", "professional"],
    requiresMicrophone: false,
    quizType: ["serious"],
    category: "theory",
  },
  {
    id: "19",
    text: "Что делать если голос сел перед выступлением?",
    options: [
      "Отменить выступление",
      "Пить лед",
      "Молчать и пить теплую воду",
      "Кричать чтобы 'разогнать' голос",
    ],
    correctAnswer: 2,
    difficulty: ["amateur", "advanced", "professional"],
    requiresMicrophone: false,
    quizType: ["serious"],
    category: "theory",
  },
  {
    id: "20",
    text: "Спойте дуэтом с записью (гармония)",
    options: ["Выполнено", "Не попал в гармонию", "Сбился с ритма"],
    correctAnswer: 0,
    difficulty: ["professional"],
    requiresMicrophone: true,
    quizType: ["serious"],
    category: "ear-training",
  },
];
